services:
  mysql:
    container_name: 'guide-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=meu_acervo'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=root'
      - 'MYSQL_ROOT_PASSWORD=rootsenha'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
